In [1]:
class Calculator:
    """Do addition, subtraction, multiplication and division."""

    def __init__(self, a, b):
        self.a = a
        self.b = b

    def addition(self):
        return self.a + self.b

    def subtraction(self):
        return self.a - self.b

    def multiplication(self):
        return self.a * self.b

    def division(self):
        try:
            return self.a / self.b
        except ZeroDivisionError:
            return 'It is impossible to divide by zero.'

my_calculator = Calculator(45, 3)

temp = my_calculator.addition()
print(temp)

temp = my_calculator.subtraction()
print(temp)

temp = my_calculator.multiplication()
print(temp)

temp = my_calculator.division()
print(temp)

48
42
135
15.0

In [2]:
# Single Inheritance
class Dog:
    def __init__(self, name):
        self.name = name

    def display_name(self):
        print(f"Dog's Name: {self.name}")

class Labrador(Dog):  # Single Inheritance
    def sound(self):
        print("Labrador woofs")

In [5]:
lab = Labrador("Tommy")
lab.display_name()

Dog's Name: Tommy

In [3]:
# Multilevel Inheritance
class GuideDog(Labrador):  # Multilevel Inheritance
    def guide(self):
        print(f"{self.name}Guides the way!")

In [4]:
# Multiple Inheritance
class Friendly:
    def greet(self):
        print("Friendly!")
        
class GoldenRetriever(Dog, Friendly):  # Multiple Inheritance
    def sound(self):
        print("Golden Retriever Barks")

In [6]:
# Parent Class
class Dog:
    def sound(self):
        print("dog sound")  # Default implementation

# Run-Time Polymorphism: Method Overriding
class Labrador(Dog):
    def sound(self):
        print("Labrador woofs")  # Overriding parent method

class Beagle(Dog):
    def sound(self):
        print("Beagle Barks")  # Overriding parent method

In [8]:
dogs = [Dog(), Labrador(), Beagle()]

for dog in dogs:
    dog.sound()

dog sound
Labrador woofs
Beagle Barks

In [9]:
# Compile-Time Polymorphism: Method Overloading Mimic
class Calculator:
    def add(self, a, b=0, c=0):
        return a + b + c  # Supports multiple ways to call add()

In [11]:
calc = Calculator()
calc.add(1, 2, 3)

6

In [12]:
calc.add(1, 2)

3

In [16]:
class Dog:
    def __init__(self, name, breed, age):
        self.name = name  # Public attribute
        self._breed = breed  # Protected attribute
        self.__age = age  # Private attribute
    # Public method
    def get_info(self):
        return f"Name: {self.name}, Breed: {self._breed}, Age: {self.__age}"

    # Getter and Setter for private attribute
    def get_age(self):
        return self.__age

    def set_age(self, age):
        self.__age = age

In [18]:
dog = Dog("Tommy", "Labrador", 5)
print(dog.name)
print(dog._breed)
print(dog.__age)

Tommy
Labrador

AttributeError: 'Dog' object has no attribute '__age'

In [19]:
print(dog.get_age())

5

In [20]:
## ERROR

In [22]:
with open('test_12.txt', 'r') as my_file:
    content = my_file.read()
    print(content)

FileNotFoundError: [Errno 2] No such file or directory: 'test_12.txt'

In [23]:
try:
    with open('test_12.txt', 'r') as my_file:
        content = my_file.read()
        print(content)
except:
    print('the file doesnt exist')

print("rest...")

the file doesnt exist
rest...

In [24]:
# try except finally

In [25]:
try:
    div = 1/0
except:
    print('the file doesnt exist')

print("rest...")

the file doesnt exist
rest...

In [26]:
div = 1/0

ZeroDivisionError: division by zero

In [28]:
## NumPy
import numpy as np
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]

In [30]:
type(arr)

numpy.ndarray

In [31]:
arr[0]

1

In [32]:
import pandas as pd

In [33]:
dataset = {
    'animal': ['Dog', 'Cat'],
    'Age': [3, 5]
}
pd_datset = pd.DataFrame(dataset)

print(pd_datset)

  animal  Age
0    Dog    3
1    Cat    5

In [35]:
df = pd.read_csv("data.csv")
# df.to_string()
df.head(6)

,tracking_id,datetime,wind_speed(m/s),atmospheric_temperature(°C),shaft_temperature(°C),blades_angle(°),gearbox_temperature(°C),engine_temperature(°C),motor_torque(N-m),generator_temperature(°C),...,windmill_body_temperature(°C),wind_direction(°),resistance(ohm),rotor_torque(N-m),turbine_status,cloud_level,blade_length(m),blade_breadth(m),windmill_height(m),windmill_generated_power(kW/h)
0,WM_33725,2019-08-04 14:33:20,94.820023,-99.000000,41.723019,-0.903423,82.410573,42.523015,2563.124522,76.665560,...,NaN,239.836388,2730.310605,42.084666,BA,Medium,2.217542,0.314065,24.281689,6.766521
1,WM_698,2018-11-05 10:13:20,241.832734,27.764785,-99.000000,-99.000000,44.104919,46.258870,2372.384119,78.129803,...,NaN,337.944723,1780.207200,107.888643,A2,Medium,4.210346,0.448494,27.262139,5.966275
2,WM_39146,2019-09-14 14:03:20,95.484724,NaN,41.855473,12.652763,42.322098,42.878552,1657.169646,67.654469,...,45.033197,227.850294,1666.049900,-42.931459,ABC,Medium,2.719475,0.302321,27.366127,2.874342
3,WM_6757,2018-12-25 15:33:20,238.819424,-99.000000,45.443914,15.115323,44.759643,47.282101,2888.134079,95.389974,...,44.827154,492.081520,1964.502895,42.744596,ABC,NaN,4.857385,0.367140,24.287767,14.851089
4,WM_21521,2019-05-04 03:13:20,10.722890,NaN,41.981183,1.715696,-17.616459,43.469852,781.695419,37.423065,...,-99.000000,259.274601,1177.516152,13.387289,AAA,Medium,NaN,0.453374,27.971650,3.519074
5,WM_17873,2019-03-22 21:03:20,93.769973,30.326226,17.970619,-99.000000,43.816430,40.815795,2119.351653,72.345126,...,101.378184,NaN,1715.244121,97.746463,ABC,Low,2.504098,0.395642,24.673292,4.945780

In [36]:
df.tail(2)

,tracking_id,datetime,wind_speed(m/s),atmospheric_temperature(°C),shaft_temperature(°C),blades_angle(°),gearbox_temperature(°C),engine_temperature(°C),motor_torque(N-m),generator_temperature(°C),...,windmill_body_temperature(°C),wind_direction(°),resistance(ohm),rotor_torque(N-m),turbine_status,cloud_level,blade_length(m),blade_breadth(m),windmill_height(m),windmill_generated_power(kW/h)
28198,WM_12173,2019-02-03 19:13:20,95.430377,26.560254,48.032624,3.051389,81.443896,44.821365,2760.64728,90.144418,...,44.973415,568.504898,1968.917692,47.562627,BCB,Low,3.001855,0.346447,47.747269,9.373239
28199,WM_33004,2019-07-30 11:43:20,43.558352,18.721231,9.220208,2.593639,40.262279,40.901975,2015.97741,69.043447,...,44.100782,320.498070,1666.526546,-8.932053,BBB,Low,NaN,0.388855,24.125408,2.860342

In [37]:
df

,tracking_id,datetime,wind_speed(m/s),atmospheric_temperature(°C),shaft_temperature(°C),blades_angle(°),gearbox_temperature(°C),engine_temperature(°C),motor_torque(N-m),generator_temperature(°C),...,windmill_body_temperature(°C),wind_direction(°),resistance(ohm),rotor_torque(N-m),turbine_status,cloud_level,blade_length(m),blade_breadth(m),windmill_height(m),windmill_generated_power(kW/h)
0,WM_33725,2019-08-04 14:33:20,94.820023,-99.000000,41.723019,-0.903423,82.410573,42.523015,2563.124522,76.665560,...,NaN,239.836388,2730.310605,42.084666,BA,Medium,2.217542,0.314065,24.281689,6.766521
1,WM_698,2018-11-05 10:13:20,241.832734,27.764785,-99.000000,-99.000000,44.104919,46.258870,2372.384119,78.129803,...,NaN,337.944723,1780.207200,107.888643,A2,Medium,4.210346,0.448494,27.262139,5.966275
2,WM_39146,2019-09-14 14:03:20,95.484724,NaN,41.855473,12.652763,42.322098,42.878552,1657.169646,67.654469,...,45.033197,227.850294,1666.049900,-42.931459,ABC,Medium,2.719475,0.302321,27.366127,2.874342
3,WM_6757,2018-12-25 15:33:20,238.819424,-99.000000,45.443914,15.115323,44.759643,47.282101,2888.134079,95.389974,...,44.827154,492.081520,1964.502895,42.744596,ABC,NaN,4.857385,0.367140,24.287767,14.851089
4,WM_21521,2019-05-04 03:13:20,10.722890,NaN,41.981183,1.715696,-17.616459,43.469852,781.695419,37.423065,...,-99.000000,259.274601,1177.516152,13.387289,AAA,Medium,NaN,0.453374,27.971650,3.519074
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28195,WM_7814,2019-01-02 02:43:20,94.765699,23.576793,45.399352,5.377222,-1.085171,48.528248,2791.600990,90.898875,...,44.242269,536.153413,1980.861921,45.909054,BB,Medium,2.774335,0.418299,24.590801,9.587934
28196,WM_32512,2019-07-26 12:53:20,94.196738,24.034329,42.068979,-99.000000,44.285153,43.487939,2207.882276,72.244645,...,43.616412,354.239825,1712.840457,36.974913,BB,Low,-3.250989,0.461531,26.051604,4.522195
28197,WM_5193,2018-12-12 02:13:20,94.160463,28.674296,45.004213,9.550358,49.377706,44.042632,2801.657374,94.814637,...,43.576510,534.209913,1951.728713,88.319152,D,Medium,NaN,0.380264,28.533850,11.096599
28198,WM_12173,2019-02-03 19:13:20,95.430377,26.560254,48.032624,3.051389,81.443896,44.821365,2760.647280,90.144418,...,44.973415,568.504898,1968.917692,47.562627,BCB,Low,3.001855,0.346447,47.747269,9.373239
28199,WM_33004,2019-07-30 11:43:20,43.558352,18.721231,9.220208,2.593639,40.262279,40.901975,2015.977410,69.043447,...,44.100782,320.498070,1666.526546,-8.932053,BBB,Low,NaN,0.388855,24.125408,2.860342

In [38]:
df.shape

(28200, 22)

In [41]:
def sound(name):
        print(f"{name} Barks")

sound("Prince")

Prince Barks

In [43]:
if __name__=="__main__": # dunder
    sound("Prince")

Prince Barks